### PR TITLE
Enhancement/gather statistics

### LINKED ISSUE #23: Gather statistics
The circuit breakers could expose statistics like:

- failed/success count requests which is covered in #40 
- Avg Response time
- Average processing time

### PR DESCRIPTION
**Pull request by MALPI**
Fixes #23 

**WIP**
Extends Failsafe Actuator by the feature to provide failure/success metrics for the used Circuit Breakers.
 
Still open: 

- Add duration of a call
- extend `Readme.md`.

### CODE REVIEW

File: src/main/java/org/zalando/failsafeactuator/domain/FailsafeBreaker.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+@Data
+public class FailsafeBreaker extends CircuitBreaker {
+
+    private final Meter failureMeter;
+    private final Meter successMeter;
+    private final Meter overallMeter;
+    private String identifier;
+
+    public FailsafeBreaker(final MetricRegistry metricRegistry, final String identifier) {
```
Comment (coders-kitchen) [inline src/main/java/org/zalando/failsafeactuator/domain/FailsafeBreaker.java]: I'm thinking if we should provide an abstraction layer around the metrics registry that would allow the users to plugin a different metrics collector, eg. prometheus.

For doing so we would need to introduce apart from the registry interface a Meter interface as well which would encapsulate the meter than.

As the default I would propose to provide a DropWizard Metrics implementation.

WDYT?

File: src/main/java/org/zalando/failsafeactuator/config/FailsafeAutoConfiguration.java [hunk 2]
```diff
@@ -30,9 +33,18 @@
...
+  public MetricRegistry metricRegistry() {
+    this.metricRegistry = new MetricRegistry();
+    return this.metricRegistry;
+  }
+
   @Bean
+  @DependsOn("metricRegistry")
   public CircuitBreakerRegistry circuitBreakerRegistry() {
-    circuitBreakerRegistry = new CircuitBreakerRegistry();
+    circuitBreakerRegistry = new CircuitBreakerRegistry(this.metricRegistry);
```
Comment (whiskeysierra) [inline src/main/java/org/zalando/failsafeactuator/config/FailsafeAutoConfiguration.java]: You shouldn't assign to instance variables here, but rather take `metricsRegistry` as a parameter.

File: src/main/java/org/zalando/failsafeactuator/domain/FailsafeBreaker.java (hunk 1 above)
Comment (whiskeysierra) [reply src/main/java/org/zalando/failsafeactuator/domain/FailsafeBreaker.java]: Spring supports [PublicMetrics](https://github.com/spring-projects/spring-boot/blob/v1.5.7.RELEASE/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/endpoint/PublicMetrics.java) for this.

File: src/main/java/org/zalando/failsafeactuator/domain/FailsafeBreaker.java [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+        this.identifier = identifier;
+        this.failureMeter = metricRegistry.meter(this.identifier+".failures");
+        this.successMeter = metricRegistry.meter(this.identifier+".success");
+        this.overallMeter = metricRegistry.meter(this.identifier+".overall");
+    }
+
+    @Override
+    public void recordResult(Object result) {
```
Comment (whiskeysierra) [inline src/main/java/org/zalando/failsafeactuator/domain/FailsafeBreaker.java]: this should be done with [event listeners](https://github.com/jhalterman/failsafe#event-listeners) rather than subclassing.

**Comment by MALPI** [comment]
Thanks for you input @whiskeysierra. Should all be considered in my last commits.

File: pom.xml [hunk 4]
```diff
@@ -44,7 +46,12 @@
 			<scope>provided</scope>
             <version>1.16.18</version>
 		</dependency>
-        <dependency>
+		<dependency>
```
Comment (whiskeysierra) [inline pom.xml]: Why do you still need this?

File: src/main/java/org/zalando/failsafeactuator/config/FailsafeAutoConfiguration.java [hunk 5]
```diff
@@ -31,12 +34,24 @@
   private CircuitBreakerRegistry circuitBreakerRegistry;
```
Comment (whiskeysierra) [inline src/main/java/org/zalando/failsafeactuator/config/FailsafeAutoConfiguration.java]: Same here, shouldn't be needed to have this assigned to an instance field.

File: src/main/java/org/zalando/failsafeactuator/config/FailsafeAutoConfiguration.java [hunk 6]
```diff
@@ -31,12 +34,24 @@
...
+  }
+
+  @Bean
   public CircuitBreakerRegistry circuitBreakerRegistry() {
     circuitBreakerRegistry = new CircuitBreakerRegistry();
     return circuitBreakerRegistry;
   }
 
   @Bean
+  @DependsOn("metricRegistry")
```
Comment (whiskeysierra) [inline src/main/java/org/zalando/failsafeactuator/config/FailsafeAutoConfiguration.java]: Not needed.

File: src/main/java/org/zalando/failsafeactuator/config/FailsafeAutoConfiguration.java [hunk 7]
```diff
@@ -31,12 +34,24 @@
...
+  public DropwizardMetric createMetric(final MetricRegistry metricRegistry) {
+    return new DropwizardMetric(metricRegistry, circuitBreakerRegistry);
+  }
+
+  @Bean
   @DependsOn("circuitBreakerRegistry")
```
Comment (whiskeysierra) [inline src/main/java/org/zalando/failsafeactuator/config/FailsafeAutoConfiguration.java]: Replace with parameter.

File: src/main/java/org/zalando/failsafeactuator/metrics/DropwizardMetric.java [hunk 8]
```diff
@@ -0,0 +1,60 @@
...
+  }
+
+  @PostConstruct
+  public void init() {
+    for (final String identifier : circuitBreakerRegistry.getConcurrentBreakerMap().keySet()) {
+      final Meter successMeter = metricRegistry.meter(identifier + SUCCESS);
+      final Meter failureMeter = metricRegistry.meter(identifier + FAILURE);
+      metricMap.put(identifier, Arrays.asList(successMeter, failureMeter));
+      Failsafe.with(circuitBreakerRegistry.getConcurrentBreakerMap().get(identifier))
+          .with(new DropwizardListener(failureMeter, successMeter));
```
Comment (whiskeysierra) [inline src/main/java/org/zalando/failsafeactuator/metrics/DropwizardMetric.java]: This probably won't work as expected.

File: src/main/java/org/zalando/failsafeactuator/config/FailsafeInjectionConfiguration.java [hunk 9]
```diff
@@ -34,9 +32,9 @@
 
   @Bean
   @Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
```
Comment (whiskeysierra) [inline src/main/java/org/zalando/failsafeactuator/config/FailsafeInjectionConfiguration.java]: Misleading because your registry actually implements a singleton pattern. Couldn't you delegate all of this work to spring?

File: pom.xml (hunk 4 above)
Comment (MALPI) [reply pom.xml]: Because Spring default metrics doesn't support `Meter`. But maybe you are right and we should rely on Spring defaults here.

Comment (whiskeysierra) [reply pom.xml]: The less dependencies the better. Gives your clients more freedom.

File: src/main/java/org/zalando/failsafeactuator/config/FailsafeInjectionConfiguration.java (hunk 9 above)
Comment (MALPI) [reply src/main/java/org/zalando/failsafeactuator/config/FailsafeInjectionConfiguration.java]: Yes, we could do this. But I would prefer to do this change in another PR.

Comment (MALPI) [reply src/main/java/org/zalando/failsafeactuator/config/FailsafeInjectionConfiguration.java]: See #45

**Comment by MALPI** [comment]
@whiskeysierra @coders-kitchen can you have another look?

File: pom.xml [hunk 10]
```diff
@@ -1,11 +1,13 @@
...
+<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+	xmlns="http://maven.apache.org/POM/4.0.0"
+	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
 
 	<modelVersion>4.0.0</modelVersion>
 
 	<groupId>org.zalando</groupId>
 	<artifactId>failsafe-actuator</artifactId>
-	<version>0.4.1</version>
+	<version>0.5.1</version>
```
Comment (whiskeysierra) [inline pom.xml]: Should a bump of the minor version set the patch back to 0, i.e. `0.5.0`?

File: src/main/java/org/zalando/failsafeactuator/aspect/Failsafe.java [hunk 11]
```diff
@@ -1,29 +1,42 @@
 /**
- * The MIT License (MIT)
- * Copyright (c) 2016 Zalando SE
+ * The MIT License (MIT) Copyright (c) 2016 Zalando SE
```
Comment (whiskeysierra) [inline src/main/java/org/zalando/failsafeactuator/aspect/Failsafe.java]: I don't believe that you actually need to put the header in every file.

File: src/main/java/org/zalando/failsafeactuator/config/FailsafeAutoConfiguration.java [hunk 12]
```diff
@@ -1,61 +1,92 @@
...
 
 /** Autoconfiguration for the FailsafeEndpoint. */
 @Configuration
 @Conditional(FailsafeAutoConfiguration.FailsafeCondition.class)
 public class FailsafeAutoConfiguration {
 
-  private CircuitBreakerRegistry circuitBreakerRegistry;
+  @Bean
+  @ConditionalOnMissingBean(MetricWriter.class)
+  public MetricWriter metricWriter() {
```
Comment (whiskeysierra) [inline src/main/java/org/zalando/failsafeactuator/config/FailsafeAutoConfiguration.java]: I wouldn't create those in here. The better approach would be to degrade and perform retries and manage circuit breakers without recording metrics.

File: src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java [hunk 13]
```diff
@@ -1,59 +1,75 @@
...
-                         try {
-                           return methodInvocation.proceed();
-                         } catch (Throwable throwable) {
-                           throw new FailsafeBreakerWrappedException(throwable);
-                         }
-                       }
-                     });
-    } catch (RuntimeException e) {
+          .with(new CountingListener<>(counterService, breaker.value()))
+          .get(
```
Comment (whiskeysierra) [inline src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java]: This won't work for methods that return a Future.

File: src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java [hunk 14]
```diff
@@ -1,59 +1,75 @@
...
+              new Callable<Object>() {
+                @Override
+                public Object call() throws Exception {
+                  try {
+                    return methodInvocation.proceed();
+                  } catch (final Throwable throwable) {
+                    throw new FailsafeBreakerWrappedException(throwable);
```
Comment (whiskeysierra) [inline src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java]: Why is this custom exception type needed?

File: pom.xml (hunk 10 above)
Comment (MALPI) [reply pom.xml]: yes, will change that

File: src/main/java/org/zalando/failsafeactuator/aspect/Failsafe.java (hunk 11 above)
Comment (MALPI) [reply src/main/java/org/zalando/failsafeactuator/aspect/Failsafe.java]: True, see #52

File: src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java (hunk 13 above)
Comment (MALPI) [reply src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java]: We should file a new Issue for that since this logic wasn't introduced by this PR.

File: src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java (hunk 14 above)
Comment (MALPI) [reply src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java]: @coders-kitchen should know. Depending on the outcome we should also tackle this on a separate issue as already mentioned before.

Comment (coders-kitchen) [reply src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java]: I prefer to have explicit exceptions in cases like this, to make it clear what the cause in case anything unexpected happen.

File: src/main/java/org/zalando/failsafeactuator/config/FailsafeAutoConfiguration.java (hunk 12 above)
Comment (coders-kitchen) [reply src/main/java/org/zalando/failsafeactuator/config/FailsafeAutoConfiguration.java]: 👍 a noop implementation in this case makes more sense

File: src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java (hunk 13 above)
Comment (MALPI) [reply src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java]: See #58

**Comment by MALPI** [comment]
@whiskeysierra @coders-kitchen I would consider this PR as done. Any further feedback?

**Comment by coders-kitchen** [comment]
@MALPI Fine from my side

**Comment by MALPI** [comment]
:+1:

File: src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java (hunk 13 above)
Comment (MALPI) [reply src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java]: Hey @whiskeysierra now as I am looking into it, it's not really clear to me what you mean here. Could maybe explain a bit more in detail or extend the issue? Would be awesome!

File: src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java (hunk 14 above)
Comment (whiskeysierra) [reply src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java]: @coders-kitchen But you're deviating from the normal behaviour of failsafe. If a user would migrate from manually using failsafe to this annotation+advice, then he/she would experience a different behaviour. I believe it would be in the best interest of everybody if both ways are 100% compatible.

File: src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java (hunk 13 above)
Comment (whiskeysierra) [reply src/main/java/org/zalando/failsafeactuator/aspect/FailsafeBreakerAspect.java]: There are two kinds of methods, sync and async. `get` is for synchronous methods. For something that returns a future, you should use `future`: https://github.com/jhalterman/failsafe#completablefuture-integration

Let's say you have a method that performs a remote request asynchronously and returns a `Future<User>`.

- `get` would only retry the synchronous part of that, i.e. if anything failed during the creation of the future, but not during
- `future` would be aware that the operation is asynchronous and it would correctly retry the asynchronous operation
